rm -f answerkey.m
rm -f myinput.m
rm -f NOES.txt
rm -f order.m
rm -f TOCSY.m
rm -f C-H_vectors.m
rm -f C-H_medium1.m
rm -f N-H_vectors.m
rm -f N-H_medium1.m
rm -f N-H_medium2.m
rm -f N-C_vectors.m
rm -f N-C_medium1.m
rm -f C-Ca_vectors.m
rm -f C-Ca_medium1.m
rm -f SHIFTS/MySHIFTS.7.model6
rm -f SHIFTX/MySHIFTX.7.model6
rm -f SPARTA/MySPARTA.7.model6
rm -f SHIFTX2/MySHIFTX2.7.model6
rm -f ca_cs
